# This file allows you to freely customize SSH instead of using 
# the default SSH setup from `nlknguyen/alpine-mpich:onbuild`
# In order to build with this, rename this file to `Dockerfile`

FROM nlknguyen/alpine-mpich:latest

# # ------------------------------------------------------------
# # Build MPI project
# # ------------------------------------------------------------

# Put all build steps here

# Notice: the current directory is ${WORKDIR:=/project}, which is 
# also the default directory where ${USER:=mpi} will SSH login to


# # ------------------------------------------------------------
# # Set up SSH Server 
# # ------------------------------------------------------------
USER root

# Add host keys
RUN cd /etc/ssh/ && ssh-keygen -A -N ''

# Config SSH Daemon
RUN  sed -i "s/#PasswordAuthentication.*/PasswordAuthentication no/g" /etc/ssh/sshd_config \
  && sed -i "s/#PermitRootLogin.*/PermitRootLogin no/g" /etc/ssh/sshd_config \
  && sed -i "s/#UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config \
  && sed -i "s/#AuthorizedKeysFile/AuthorizedKeysFile/g" /etc/ssh/sshd_config
 
# Unlock non-password USER to enable SSH login
RUN passwd -u ${USER}

# Set up user's public and private keys
ENV SSHDIR /home/${USER}/.ssh/
RUN mkdir -p ${SSHDIR}

# COPY ssh/config ${SSHDIR}/config
# COPY ssh/id_rsa ${SSHDIR}/id_rsa
# COPY ssh/id_rsa.pub ${SSHDIR}/id_rsa.pub
COPY ssh/ ${SSHDIR}/
RUN cat ${SSHDIR}/*.pub >> ${SSHDIR}/authorized_keys
# COPY ssh/id_rsa.pub ${SSHDIR}/authorized_keys

RUN chmod -R 600 ${SSHDIR}* && \
    chown -R ${USER}:${USER} ${SSHDIR}

# Default working directory when user login 
RUN echo "cd $WORKDIR" >> /home/${USER}/.profile

# # ------------------------------------------------------------
# # Start SSH Server
# # ------------------------------------------------------------
EXPOSE 22

# CMD ["/usr/sbin/sshd","-D", "-d", "-e"]
# -e for verbose; -d for debug (auto shutdown daemon when connection closes)
CMD ["/usr/sbin/sshd", "-D", "-e"]
